### ISSUE TITLE
2018 Content Spec: AMD 1: Duplication in Annex B

### ISSUE THREAD

**Issue by johnsim** [cta-wave/content-specification-task-force#12]
(Annex B) last three paragraphs Chris Poole comment: ‘There is quite a lot of duplication between these paragraphs and those preceding.’ Agree, but deferred to subsequent draft of the specification.

**Comment by KilroyHughes** [comment]
Include cleanup in Amendment 1.

**Comment by johnsim** [comment]
Agreed in October 24, 2018 conference call - Approve all changes to Annex B.
