### ISSUE TITLE
2018 Content Spec: AMD 1: Add DTS-HD Audio Media Profile

### ISSUE THREAD

**Issue by johnsim** [cta-wave/content-specification-task-force#13]
See https://github.com/cta-wave/content-specification-task-force/wiki/Media-Profile:-CMAF-DTS-HD-Audio-('dts1')

**Comment by pmaness** [comment]
Qualcomm raised two issues with ETSI TS 102 114 v1.5.1 Annex H. 
1.) In clause H.1.4. it currently reads as "A DTS-HD audio sample is described in clause E.2. Audio samples in DTS-HD CMAF tracks shall always be presented in presentation order. Each DTS-HD audio sample is a sync sample."
The proposed revision is as follows:
"A DTS-HD audio sample is described in clause E.2. Each DTS-HD audio sample is a sync sample."
(explanation: the offending sentence is not needed).
2.) In clause  H.1.7. 
There are two problems in this clause, one claiming the brand is required, the other with the brand name. The brand name is intended to be 'dts1' and not 'ts1'. There should not be a mandate to use the brand in 'ftyp'.
This proposal is to remedy the problems as follows:
Clause H.1.7 will be revised as follows:
The file type box of a DTS-HD track may contain the brand 'dts1'. If the 'dts1' brand is present in the file type box, then the track shall comply with the requirements of the definition described in the present Annex.
If these revisions are acceptable, they would be made in TS 102 114v1.6.1 which can get underway soon.

**Comment by pmaness** [comment]
Additional update to improve H.2.2:
Replace the existing text with the following proposed text:
A DTS-HD track conforming to the 'dts1' Media Profile shall conform to clause 10.2 of ISO/IEC 23000-19 [4],  Annex E of this specification and one of 'dtsc', 'dtsh', or 'dtse' sample entries as defined in Table E-2.

**Comment by johnsim** [comment]
I have added DTS-HD to Table 2 and DTS-HD to the normative reference section 2.1
