### ISSUE TITLE
Status of CMAF Amendment 2 - Supplemental Data

### ISSUE THREAD

**Issue by johnsim** [cta-wave/content-specification-task-force#17]
CMAF Amd2 (DAM) is referenced by the Dolby Vision Media Profile. Is it adequately complete to be referenced in this fashion, and if not, how complete must it be before referenced.

**Comment by rdoherty0** [comment]
The DIS (DAM2) ballot closes 6-July.  The specification is already more mature than the CMAF specification when WAVE worked on the Content Specification.

In addition, the functionality is not new -- it has been already published in the existing CMAF specification.  The Amd2 simply codifies the behavior and gives it a name, but doesn't actually introduce new functionality.  The functionality is already published in CMAF, and is used for 608/608 subtitles in the published spec.

**Comment by johnsim** [comment]
Amendment is being incorporated into Edition 2 of CMAF. Document for Amendment 2 will be available July 23, 2018 in MPEG repository.
