### ISSUE TITLE
Playback Requirements for DV Profile

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/content-specification-task-force#20]
The draft DPC spec says: "if a device claims to support playback of a specific CMAF media profile, then this specification defines the requirements that need to be fulfilled". At least for all CMAF video media profile this all results in testable requirements. What are the requirements for Dolby Vision? Where are they documented?

**Comment by rdoherty0** [comment]
All non-CMAF media profiles have this problem/requirement.  This is not specific to Dolby Vision, and needs to be solved in a general way, presumably by the DPTF.

Each media profile has a referenced specification, so requirements to conform to that specification is an important first step.  The group needs to discuss this issue.

**Comment by haudiobe** [comment]
For video profiles, you need to be able to decode. Rendering is up to the device. For Dolby Vision, is it sufficient to
a) ignore SEI messages
b) process SEI messages but ignore the content
c) process SEI messages and do some minimum processing on the rendering
d) have passed a certification process
We want to create interoperabililty in Internet Streaming and we need to answer these questions.

**Comment by rdoherty0** [comment]
Dolby Vision is a supplemental profile which consists of optional metadata which can be used to modify the image -- this is not the same as a video profile.  We can and should define testable requirements, but they are in regards to correct parsing of the metadata specification as defined in the referenceable standard.  Nevertheless the SEI messages are optional, so a compliant client could choose a-d as it desires.  

For a certification process -- WAVE has several media profiles that have external certification processes (notably for audio codecs) but as a group we have yet to consider how to document those external certifications.

**Comment by haudiobe** [comment]
So it means that a WAVE device ignoring the SEI messages conforms to the profile? Does not seem to create any value to me.

**Comment by rdoherty0** [comment]
There is significant value to any WAVE profile including the cdv1 profile.. This includes the clarity of content specification, important references, test vectors, conformance testing, signaling conventions, etc.  There is tremendous value to implementers.

**Comment by johnsim** [comment]
Resolution: Dolby Vision specific behavior of ‘cdv1’ is covered under a certification  program outside of WAVE. Other media profiles have such certification  programs. Issue 20 should not block publication of ‘cdv1’ in  Amendment 1, providing that it is documented in such a way that WAVE can reference it.

**Comment by johnsim** [comment]
Reopen until we verify that the documentation can be referenced by WAVE.

**Comment by rdoherty0** [comment]
The resolution listed does not match the consensus.  This was revisited in **2018 WAVE Face to Face Meeting; IBC**, from the notes: **Draft Meeting Report from Tuesday, 2018‐09‐18** :
_Topic #13: Conclude discussions on CDV1
Consensus: WAVE does not define any playback requirements for supplemental media profiles._ 

While this conclusion is likely overly broad for all Supplemental Media Profiles, I believe it accurately represents the consensus about cdv1, and there fore suggest this bug can be closed with "No requirements are necessary"

**Comment by johnsim** [comment]
Based on this consensus at the F2F meeting, I am closing this issue.
