### ISSUE TITLE
2018 Content Spec: AMD 1: Add the xHE-AAC media profile

### ISSUE THREAD

**Issue by irajs** [cta-wave/content-specification-task-force#22]
xHE-AAC was added into MPEG CMAF spec in AMD2. Please add this media profile to the current content spec:

https://github.com/cta-wave/content-specification-task-force/wiki/Audio-profile-using-the-xHE-AAC-Audio-Media-Profile-as-defined-in-CMAF-('cxha')

**Comment by johnsim** [comment]
Awaiting Steering Committee Approval

**Comment by johnsim** [comment]
Steering Committee approval, Thursday October 18, 2018.
