### ISSUE TITLE
2018 Content Spec - CTA Legal Boilerplate

### ISSUE THREAD

**Issue by johnsim** [cta-wave/content-specification-task-force#4]
CTA legal boilerplate. I did not adopt the proposed change – but instead will advise CTA that they need to review the use of CEA versus CTA in their boilerplate.

**Comment by johnsim** [comment]
Bill Rose to follow up with Mike to see if this is resolved.

**Comment by gitwjr** [comment]
Emailed Mike. Waiting to hear back. 

 

Bill

**Comment by johnsim** [comment]
This issue was resolved before publication of the April 2018 draft.
