### ISSUE TITLE
[wtwg review] Editorial Updates for 2020

### ISSUE THREAD

**Issue by JohnRiv** [cta-wave/content-specification-task-force#48]
I noticed some minor editorial change that should be made now that it's the 2020 edition instead of 2019:

**1. Scope:**
"This 2019 Edition additionally defines..."
🔽 
"**The** 2019 Edition additionally **defined**..."

**2.2 Informative References**
Would be good to update the WMAS reference to _one_ of the following:
- Remove it (it seems to not be referenced)
- Update the URL to the official CTA URL for 2019: https://cdn.cta.tech/cta/media/media/resources/standards/pdfs/cta-5000-b-final_v2.pdf
- Update the URL to the official W3C URL for 2019: https://www.w3.org/2019/12/webmediaapi.html
- Update "Web Media API Snapshot 2019, Community Group Report, 4 December 2019" to "Web Media API Snapshot 2020, Community Group Report, December 2020" (and keep the URL as the Editor's Draft)

**7.1 Introduction:**
"This 2019 edition specifies..."
🔽 
"**The** 2019 edition **specified**..."

**Comment by johnsim** [comment]
Thanks for the catches, John. I agree with all of the changes.

**Comment by ablasgen** [comment]
These changes have been made to the TWG review draft.
