### ISSUE TITLE
2018 Content Spec: AMD 1: Clarify "continuous duration" in Figure 3

### ISSUE THREAD

**Issue by johnsim** [cta-wave/content-specification-task-force#5]
2.	(Section 3.1) Clarity – unclear what “continuous duration” means in Figure 3

**Comment by johnsim** [comment]
(Kilroy) Taken directly from CMAF - two things that could be added - reference presentation time calculation in CMAF and add language explaining continuous duration - raised related issue with WAVE programs. (Will) "no gaps and no overlapping" - on the CMAF presentation timeline - is better description than "continuous".
RESOLUTION: add language where we reference Figure 3. Kilroy can propose language as a comment.

**Comment by KilroyHughes** [comment]
Add to this existing text following Figure 1:  
"CMAF specifies CMAF Switching Sets that contain one or more CMAF Tracks with time-aligned CMAF Fragments, typically encoded at different bitrates and qualities. CMAF Fragments with the same decode timestamp are switchable alternatives. " 

Add:

Figure 2 illustrates time aligned CMAF Fragments in a CMAF Switching Set. Fragment decode and presentation times are "continuous", meaning there are no gaps or overlaps in the decode time and duration of CMAF Fragments, or the presentation time of the media samples in each CMAF Track. 

[ed note:  Re-label and reorder current Figure 3 showing Switching Set Tracks and Fragments to Figure 2, and locate immediately following the added text. ]

**Comment by johnsim** [comment]
Text added and moved figure as described by @KilroyHughes
